apiVersion: batch/v1
kind: CronJob
metadata:
  name: scratch-cleanup
spec:
  schedule: "*/5 * * * *"  # Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scratch-cleanup
            image: scratch-cleanup:latest  # Replace with your image
            args:
              - "/mnt/cache"     # Argument 1 for the script
            volumeMounts:
              - name: cache-volume
                mountPath: /mnt/cache  # This is where the PVC will be mounted in the container
          volumes:
            - name: my-pvc-volume
              persistentVolumeClaim:
                claimName: my-existing-pvc  # Replace with the name of your PVC
          restartPolicy: OnFailure  # Restart if the job fails
