apiVersion: batch/v1
kind: CronJob
metadata:
  name: scratch-cleanup
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scratch-cleanup
            image: eccr.ecmwf.int/c3s-applications/jupyter-scratch-cleanup
            args:
              - "/mnt/cache" # path to clean up
            volumeMounts:
              - name: cache-volume
                mountPath: /mnt/cache  # This is where the PVC will be mounted in the container
          volumes:
            - name: cache-volume
              persistentVolumeClaim:
                claimName: scratch
          restartPolicy: OnFailure  # Restart if the job fails
