apiVersion: batch/v1
kind: CronJob
metadata:
  name: scratch-cleanup
spec:
  schedule: "0 * * * *" # run hourly
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
          - name: scratch-cleanup
            image: eccr.ecmwf.int/c3s-applications/scratch-cleanup
            args:
              - "/mnt/cache" # path to clean up
              - "--high"     # percentage when to start cleaning up
              - "80"
              - "--time-order"
              - "mtime"      # Choose time-stamp to order files by (atime is not currently supported)
              - "--preserve-dirs"
            resources:
              requests:
                memory: "512Mi"  # Minimum memory requested
                cpu: "1000m"      # Minimum CPU requested
              limits:
                memory: "1024Mi"  # Maximum memory allowed
                cpu: "1500m"      # Maximum CPU allowed
            volumeMounts:
              - name: cache-volume
                mountPath: /mnt/cache  # This is where the PVC will be mounted in the container
          volumes:
            - name: cache-volume
              persistentVolumeClaim:
                claimName: scratch
          restartPolicy: OnFailure  # Restart if the job fails
