apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs
parameters:
  adminId: admin
  adminSecretName: cephfs-provisioner
  adminSecretNamespace: cephfs-provisioner
  claimRoot: /volumes
  cluster: ceph
  deterministicNames: "true"
  monitors: ""
provisioner: ceph.com/cephfs
reclaimPolicy: Retain
volumeBindingMode: Immediate
