allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-manila-cephfs-atime
parameters:
  cephfs-mounter: kernel
  csi.storage.k8s.io/controller-expand-secret-name: csi-manila-secrets
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-manila-secrets
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-manila-secrets
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: csi-manila-secrets
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  type: cephfsnative1
# These option do not work with the current cephfs provisions/cloud settings
#   csi.storage.k8s.io/mount-options: "atime"
# mountOptions:
#   - strictatime

provisioner: cephfs.manila.csi.openstack.org
reclaimPolicy: Delete
volumeBindingMode: Immediate
